import { Geist, Geist_Mono , Open_Sans } from "next/font/google";
import "./globals.css";
import LenisProvider from "./LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Open_San = Open_Sans({
  variable: "--font-Open_Sans",
  subsets: ["latin"],
  weight: ["400" , "500", "700" , "800"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Open_San.variable} antialiased`}
        data-new-gr-c-s-check-loaded="14.1254.0"
        data-gr-ext-installed=""
        cz-shortcut-listen="true"
      >
        <LenisProvider>
        {children}
        </LenisProvider>
      </body>
    </html>
  );
}
